# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - clone
  - unitTest
  - build
  - test

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "adamcooper1386/kp"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: clone

  unitTests:
    title: "Running unit and single service request test"
    type: parallel
    stage: unitTest
    steps:
      webUnitTests:
        type: freestyle
        image: "ubuntu:latest" # The image in which command will be executed
        working_directory: "${{clone}}/web" # Running command where code cloned
        commands:
          - "yarn install"
          - "yarn test"

    # build:
    #title: "Building Docker image"
    #type: "build"
    #image_name: "adamcooper1386/kp"
    #working_directory: "${{clone}}/web"
    #tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    #dockerfile: "./Dockerfile"
    #stage: "build"



