pipeline {
    agent any
    stages {
        stage('build') {
            steps {
		echo "Build the docker image"
		script {
                    docker.build('adamcooper1386/ketopal')
		}
            }
        }
    }
}
